version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: bm_es
    environment:
      - node.name=bm_es
      - cluster.name=bm-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - bm_esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: bm_kibana
    ports: 
      - "5601:5601"
    networks:
      - esnet

volumes:
  bm_esdata01:
    driver: local
networks:
  esnet: